version: 0.1
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package \
        --template-file samTemplate.yml \
        --s3-bucket ci-cd-needs \
        --output-template-file NewSamTemplate.yml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yml
